### ISSUE TITLE
Добавление английских названий основных понятий

### ISSUE THREAD

**Issue by larayoda** [russsiq/laravel-docs-ru#7]
Скорее, предложение! Отличный проект, но было бы неплохо добавить английские название самых базовых концепций/компонентов. Хотя бы в заголовки. А то недавно на собесе попался вопрос "что такое черты в Laravel" (люди проверяли, а вдруг чел на русском читает документацию). 

Посредники - Middleware
Поставщики служб - ServiceProvider
и т.п.

**Comment by russsiq** [comment]
И что вы ответили на вопрос про «чертов»?

**Comment by larayoda** [comment]
> И что вы ответили на вопрос про «чертов»?
На самом собесе я так и не сообразил, что "черта" - это трейт)))

**Comment by russsiq** [comment]
Просто-напросто им не нужен работник.

Что касается самого вопроса, то я может быть подумаю. «Сервис-провайдеры», конечно, звучнее и понятнее )
